<?xml version="1.0" encoding="utf-8"?><Database Name="DuLieu" Class="DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-TTK;Initial Catalog=DuLieu;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DuLieuConnectionString" Provider="Microsoft.Data.SqlClient" />
  <Table Name="dbo.tblKhach" Member="tblKhaches">
    <Type Name="tblKhach">
      <Column Name="Makhach" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblHang" Member="tblHangs">
    <Type Name="tblHang">
      <Column Name="Mahang" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaChatLieu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGiaNhap" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DonGiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Anh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>